spring.application.name=shop
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver



# JDBC ?? URL (??? ??? ?? ??)
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

#???
#spring.datasource.username=system
# ????
#spring.datasource.password=1234qwer

# 1. ??? ???? ??
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 2. JDBC URL (??: TNS_ADMIN ?? ??? ??? ?? ??? ?????)
# ?: D:/projects/my-shop/src/main/resources/wallet
#spring.datasource.url=jdbc:oracle:thin:@projectdb_high?TNS_ADMIN=D:/apishop/src/main/resources/wallet
spring.datasource.url=jdbc:oracle:thin:@projectdb_high?TNS_ADMIN=/app/resources/wallet

# 3. DB ?? ??
spring.datasource.username=ADMIN
spring.datasource.password=x85410217Z!@#

# ??????? DB? ???? ?????? ???? ?? ? ???? ??? ??
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# (?? ??) ?? jakarta ?? ??? ????? ?? ??
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

mybatis.mapper-locations=classpath:mapper/*.xml

# =======================================================
# 1. JWT (JSON Web Token) ??
# =======================================================

# JWT Secret Key ??. (??)
# ? ?? JwtTokenProvider ???? @Value("${jwt.secret}")?? ?????.
# ??? ?? Base64? ???? ??? (256?? ??)? ???? ???.
jwt.secret=U2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uRXhhbXBsZVN0cmluZw==

#live ??? ?? ???
spring.devtools.livereload.enabled=true


# application.properties
spring.profiles.include=kakao

# --- kakao ---
kakao.client-id=41995ca715ee4777c817d8ba08ac344f
kakao.client-secret=MOMLelfYpbXFV5yxznC2eTstqCZC4vzp
#kakao.redirect-uri=http://localhost:8080/api/auth/kakao/callback
kakao.redirect-uri=https://shop-app1.azurewebsites.net/api/auth/kakao/callback


#?? ??? ?????
spring.servlet.multipart.maxFileSize=20MB
#??? ?? ?? ??
spring.servlet.multipart.maxRequestSize=100MB
#??????????
#itemImgLocation=D:/apishop/item
#??? ??? ??
#uploadPath=file:///D:/apishop/

# ?? ?????? ??? ?? ??? ???(???)? ?? URL ??? ??
itemImgLocation=item
itemImgBaseUrl=https://objectstorage.ap-chuncheon-1.oraclecloud.com/n/axgehivkhfgt/b/item/o/

# OCI ?? ??
oci.tenant-id=ocid1.tenancy.oc1..aaaaaaaauoahbfhfb462cubl6vjyjnqbmxsndiach6ucpqlvf57hkzia4jvq
oci.user-id=ocid1.user.oc1..aaaaaaaa6a4me6zz4pdjvp6n5nit5yltwmit3qiemocfuhnuauipuguz4nda
oci.fingerprint=49:36:7e:9d:9e:1a:36:83:a8:c4:7d:38:42:9a:ee:d3

#oci.private-key-path=D:/apishop/src/main/resources/wallet/private_key.pem
oci.private-key-path=/app/resources/wallet/private_key.pem

oci.region=ap-chuncheon-1
oci.namespace=axgehivkhfgt
oci.bucket-name=item

# ????? localhost, Azure ??(Environment Variables)??? Azure URL ??
app.cors.allowed-origins=http://localhost:3000,http://localhost:8080,https://shop-app1.azurewebsites.net
defaultDomain=https://shop-app1.azurewebsites.net
#defaultDomain=http://localhost:3000

spring.datasource.hikari.max-lifetime=1680000
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000