spring.application.name=shop
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# JDBC ?? URL (??? ??? ?? ??)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

#???
spring.datasource.username=system
# ????
spring.datasource.password=1234qwer

mybatis.mapper-locations=classpath:mapper/*.xml

# =======================================================
# 1. JWT (JSON Web Token) ??
# =======================================================

# JWT Secret Key ??. (??)
# ? ?? JwtTokenProvider ???? @Value("${jwt.secret}")?? ?????.
# ??? ?? Base64? ???? ??? (256?? ??)? ???? ???.
jwt.secret=U2VjcmV0S2V5Rm9ySldUVG9rZW5HZW5lcmF0aW9uRXhhbXBsZVN0cmluZw==

#live ??? ?? ???
spring.devtools.livereload.enabled=true


# application.properties
spring.profiles.include=kakao

# --- kakao ---
kakao.client-id=41995ca715ee4777c817d8ba08ac344f
kakao.client-secret=MOMLelfYpbXFV5yxznC2eTstqCZC4vzp
kakao.redirect-uri=http://localhost:8080/api/auth/kakao/callback



#?? ??? ?????
spring.servlet.multipart.maxFileSize=20MB
#??? ?? ?? ??
spring.servlet.multipart.maxRequestSize=100MB
#??????????
itemImgLocation=D:/shop/item
#??? ??? ??
uploadPath=file:///D:/shop/