spring.application.name=shop
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# JDBC ?? URL (??? ??? ?? ??)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe

#???
spring.datasource.username=system
# ????
spring.datasource.password=

mybatis.mapper-locations=classpath:mapper/*.xml

# =======================================================
# 1. JWT (JSON Web Token) ??
# =======================================================

# JWT Secret Key ??. (??)
# ? ?? JwtTokenProvider ???? @Value("${jwt.secret}")?? ?????.
# ??? ?? Base64? ???? ??? (256?? ??)? ???? ???.
jwt.secret=

#live ??? ?? ???
spring.devtools.livereload.enabled=true


# application.properties
spring.profiles.include=kakao

# --- kakao ---
kakao.client-id=
kakao.client-secret=
kakao.redirect-uri=http://localhost:8080/api/auth/kakao/callback



#?? ??? ?????
spring.servlet.multipart.maxFileSize=20MB
#??? ?? ?? ??
spring.servlet.multipart.maxRequestSize=100MB
#??????????
itemImgLocation=D:/apishop/item
#??? ??? ??
uploadPath=file:///D:/apishop/
